// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plans

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PlansClient is the client API for Plans service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlansClient interface {
	GetPlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*FUPPlanResponse, error)
}

type plansClient struct {
	cc grpc.ClientConnInterface
}

func NewPlansClient(cc grpc.ClientConnInterface) PlansClient {
	return &plansClient{cc}
}

var plansGetPlanStreamDesc = &grpc.StreamDesc{
	StreamName: "GetPlan",
}

func (c *plansClient) GetPlan(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*FUPPlanResponse, error) {
	out := new(FUPPlanResponse)
	err := c.cc.Invoke(ctx, "/Plans/GetPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlansService is the service API for Plans service.
// Fields should be assigned to their respective handler implementations only before
// RegisterPlansService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type PlansService struct {
	GetPlan func(context.Context, *Plan) (*FUPPlanResponse, error)
}

func (s *PlansService) getPlan(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Plans/GetPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetPlan(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterPlansService registers a service implementation with a gRPC server.
func RegisterPlansService(s grpc.ServiceRegistrar, srv *PlansService) {
	srvCopy := *srv
	if srvCopy.GetPlan == nil {
		srvCopy.GetPlan = func(context.Context, *Plan) (*FUPPlanResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetPlan not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Plans",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetPlan",
				Handler:    srvCopy.getPlan,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "plans/plans.proto",
	}

	s.RegisterService(&sd, nil)
}
